variable "org_billing_email" {}
variable "org_name" {}
variable "org_description" {}
variable "org_company" {}
variable "org_email" {}
variable "org_location" {}
variable "org_has_organization_projects" {}
variable "org_has_repository_projects" {}
variable "org_default_repository_permission" {}
variable "org_members_can_create_repositories" {}
variable "org_members_can_create_public_repositories" {}
variable "org_members_can_create_private_repositories" {}
variable "org_members_can_create_internal_repositories" {}
variable "org_members_can_create_pages" {}
variable "org_members_can_create_public_pages" {}
variable "org_members_can_create_private_pages" {}
variable "org_members_can_fork_private_repositories" {}
variable "org_web_commit_signoff_required" {}
variable "org_advanced_security_enabled_for_new_repositories" {}
variable "org_dependabot_alerts_enabled_for_new_repositories" {}
variable "org_dependabot_security_updates_enabled_for_new_repositories" {}
variable "org_dependency_graph_enabled_for_new_repositories" {}
variable "org_secret_scanning_enabled_for_new_repositories" {}
variable "org_secret_scanning_push_protection_enabled_for_new_repositories" {}